# Generated by Django 5.2 on 2025-04-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('maindescription', models.TextField()),
                ('interested', models.CharField(blank=True, choices=[('Job', 'Job'), ('Study', 'Study')], max_length=20, null=True)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.qualification')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.subject')),
            ],
        ),
    ]
