# Generated by Django 5.2 on 2025-05-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Career',
        ),
    ]
